### ISSUE TITLE
pylibrelinkup.exceptions.AuthenticationError: Invalid login credentials

### ISSUE THREAD

**Issue by Kanzll** [robberwick/pylibrelinkup#24] opened 2024-11-01 15:20 UTC
Hello,
I tested pylibrelinkup, and I want to thank you for your work.
I used my credantials, I get `invalid login credentials` error, I tested although credentials on libreview.com and they're good.

here is complete response: 
```
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/pylibrelinkup/pylibrelinkup.py", line 60, in authenticate
    login_response = LoginResponse.model_validate(data)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/pydantic/main.py", line 568, in model_validate
    return cls.__pydantic_validator__.validate_python(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 21 validation errors for LoginResponse
data.user.id
  Field required [type=missing, input_value={'accountType': 'pat', 'c..., 'uiLanguage': 'fr-CA'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
data.user.firstName
  Field required [type=missing, input_value={'accountType': 'pat', 'c..., 'uiLanguage': 'fr-CA'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
data.user.lastName
  Field required [type=missing, input_value={'accountType': 'pat', 'c..., 'uiLanguage': 'fr-CA'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
data.user.email
  Field required [type=missing, input_value={'accountType': 'pat', 'c..., 'uiLanguage': 'fr-CA'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
data.user.communicationLanguage
  Field required [type=missing, input_value={'accountType': 'pat', 'c..., 'uiLanguage': 'fr-CA'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
data.user.uom
  Field required [type=missing, input_value={'accountType': 'pat', 'c..., 'uiLanguage': 'fr-CA'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
data.user.dateFormat
  Field required [type=missing, input_value={'accountType': 'pat', 'c..., 'uiLanguage': 'fr-CA'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
data.user.timeFormat
  Field required [type=missing, input_value={'accountType': 'pat', 'c..., 'uiLanguage': 'fr-CA'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
data.user.emailDay
  Field required [type=missing, input_value={'accountType': 'pat', 'c..., 'uiLanguage': 'fr-CA'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
data.user.system
  Field required [type=missing, input_value={'accountType': 'pat', 'c..., 'uiLanguage': 'fr-CA'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
data.user.details
  Field required [type=missing, input_value={'accountType': 'pat', 'c..., 'uiLanguage': 'fr-CA'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
data.user.created
  Field required [type=missing, input_value={'accountType': 'pat', 'c..., 'uiLanguage': 'fr-CA'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
data.user.lastLogin
  Field required [type=missing, input_value={'accountType': 'pat', 'c..., 'uiLanguage': 'fr-CA'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
data.user.programs
  Field required [type=missing, input_value={'accountType': 'pat', 'c..., 'uiLanguage': 'fr-CA'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
data.user.dateOfBirth
  Field required [type=missing, input_value={'accountType': 'pat', 'c..., 'uiLanguage': 'fr-CA'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
data.user.practices
  Field required [type=missing, input_value={'accountType': 'pat', 'c..., 'uiLanguage': 'fr-CA'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
data.user.devices
  Field required [type=missing, input_value={'accountType': 'pat', 'c..., 'uiLanguage': 'fr-CA'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
data.user.consents
  Field required [type=missing, input_value={'accountType': 'pat', 'c..., 'uiLanguage': 'fr-CA'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
data.messages
  Field required [type=missing, input_value={'step': {'type': 'pp', '...6, 'duration': 3600000}}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
data.notifications
  Field required [type=missing, input_value={'step': {'type': 'pp', '...6, 'duration': 3600000}}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
data.invitations
  Field required [type=missing, input_value={'step': {'type': 'pp', '...6, 'duration': 3600000}}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/anaconda3/lib/python3.12/site-packages/pylibrelinkup/pylibrelinkup.py", line 65, in authenticate
    raise AuthenticationError("Invalid login credentials")
pylibrelinkup.exceptions.AuthenticationError: Invalid login credentials
```

Thank you !

**Comment by robberwick** [comment] 2024-11-01 15:29
Hi @Kanzll - thanks for the report. I'll pick this up and take a look asap.

**Comment by robberwick** [comment] 2024-11-01 19:41
I think that rather than being an authentication error, it's actually an issue with the response you're receiving to your login request.  I'm wondering if you're receiving a login response which I've not seen before, so isn't being gracefully handled.

If you're using the default `api_url` parameter for the `login` method, then could you try the script below and share what the response json is? You should be able to run it from anywhere, as it doesn't rely on anything but the python stdlib. That would help diagnose the problem.

```python
import json
import urllib.request
import urllib.error

def main(email: str, password: str):
    url = "https://api.libreview.io/llu/auth/login"
    headers = {
        "accept-encoding": "gzip",
        "cache-control": "no-cache",
        "connection": "Keep-Alive",
        "content-type": "application/json",
        "product": "llu.android",
        "version": "4.7.0",
    }
    login_args = {
        "email": email,
        "password": password
    }

    request = urllib.request.Request(url, data=json.dumps(login_args).encode(), headers=headers, method="POST")

    try:
        with urllib.request.urlopen(request) as response:
            response_data = response.read()
            response_json = json.loads(response_data)
            print(json.dumps(response_json, indent=4))
    except urllib.error.HTTPError as e:
        print(f"HTTPError: {e.code} - {e.reason}")
    except urllib.error.URLError as e:
        print(f"URLError: {e.reason}")

if __name__ == "__main__":
    login_email = input("Enter your email: ")
    login_password = input("Enter your password: ")
    main(email=login_email, password=login_password)
```

if you're not using the default, let me know what value you're using, and i can update the script accordingly.

**Comment by Kanzll** [comment] 2024-11-02 04:03
I received an error
```
Traceback (most recent call last):
  File "/Users/delta/Documents/Coding/libreview/test.py", line 36, in <module>
    main(email=login_email, password=login_password)
  File "/Users/delta/Documents/Coding/libreview/test.py", line 25, in main
    response_json = json.loads(response_data)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/json/__init__.py", line 341, in loads
    s = s.decode('utf-8', 'surrogatepass')
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte
```

**Comment by robberwick** [comment] 2024-11-02 07:58
that's my fault - the response is gzip'ed🤦 

try this:

```python
import gzip
import json
import urllib.request
import urllib.error

def main(email: str, password: str):
    url = "https://api.libreview.io/llu/auth/login"
    headers = {
        "accept-encoding": "gzip",
        "cache-control": "no-cache",
        "connection": "Keep-Alive",
        "content-type": "application/json",
        "product": "llu.android",
        "version": "4.7.0",
    }
    login_args = {
        "email": email,
        "password": password
    }

    request = urllib.request.Request(url, data=json.dumps(login_args).encode(), headers=headers, method="POST")

    try:
        with urllib.request.urlopen(request) as response:
            response_data = response.read()
            if response.info().get('Content-Encoding') == 'gzip':
                response_data = gzip.decompress(response_data)
            response_json = json.loads(response_data.decode('utf-8'))
            print(json.dumps(response_json, indent=4))
    except urllib.error.HTTPError as e:
        print(f"HTTPError: {e.code} - {e.reason}")
    except urllib.error.URLError as e:
        print(f"URLError: {e.reason}")

if __name__ == "__main__":
    login_email = input("Enter your email: ")
    login_password = input("Enter your password: ")
    main(email=login_email, password=login_password)
```

**Comment by Kanzll** [comment] 2024-11-02 16:11
It works now, here is json response 
```
{
    "status": 4,
    "data": {
        "step": {
            "type": "pp",
            "componentName": "AcceptDocument",
            "props": {
                "reaccept": true,
                "titleKey": "Common.privacyPolicy",
                "type": "pp"
            }
        },
        "user": {
            "accountType": "pat",
            "country": "CA",
            "uiLanguage": "fr-CA"
        },
        "authTicket": {
            "token": "xxx",
            "expires": 1730567336,
            "duration": 3600000
        }
    }
}
```

**Comment by robberwick** [comment] 2024-11-02 17:03
ok, so that's showing that you need to accept the privacy policy, which is similar to the Terms of Use acceptance issue described in #11 . I'll put in a patch to handle that response, but in the meantime, if you do as [described here](https://github.com/robberwick/pylibrelinkup/issues/11#issuecomment-2374538262), and log out of your librelinkup app on your phone and then log back in again, you'll be prompted to accept that privacy policy there, and once that's done you should be good to go.

**Comment by robberwick** [comment] 2024-11-02 17:58
[v0.4.0](https://github.com/robberwick/pylibrelinkup/releases/tag/v0.4.0) has been published now, which should handle that privacy policy a bit more gracefully, by at least raising an appropriate `PrivacyPolicyError` exception, rather than a misleading `AuthenticationError`

https://pypi.org/project/pylibrelinkup/0.4.0/

**Comment by Kanzll** [comment] 2024-11-02 18:25
Thanks @robberwick, I used [this link](https://libreview-unofficial.stoplight.io/docs/libreview-unofficial/2820132fdbd4f-accept-terms) to accept pp by changing  POST API link (tou -> pp), test script return a json with all my informations now. 

I updated package to 0.4.0 but the error still there :(
```
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/pylibrelinkup/pylibrelinkup.py", line 66, in authenticate
    login_response = LoginResponse.model_validate(data)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/pydantic/main.py", line 568, in model_validate
    return cls.__pydantic_validator__.validate_python(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.ValidationError: 4 validation errors for LoginResponse
data.user.system.messages.lluGettingStartedBanner
  Field required [type=missing, input_value={'firstUsePhoenix': 17026...comeScreen': 1702669161}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
data.user.system.messages.lluNewFeatureModal
  Field required [type=missing, input_value={'firstUsePhoenix': 17026...comeScreen': 1702669161}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
data.user.system.messages.lluOnboarding
  Field required [type=missing, input_value={'firstUsePhoenix': 17026...comeScreen': 1702669161}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
data.invitations
  Input should be a valid list [type=list_type, input_value=None, input_type=NoneType]
    For further information visit https://errors.pydantic.dev/2.8/v/list_type

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/uu/Documents/Coding/libreview/main.py", line 3, in <module>
    client.authenticate()
  File "/opt/anaconda3/lib/python3.12/site-packages/pylibrelinkup/pylibrelinkup.py", line 71, in authenticate
    raise AuthenticationError("Invalid login credentials")
pylibrelinkup.exceptions.AuthenticationError: Invalid login credentials
```

**Comment by robberwick** [comment] 2024-11-02 18:34
actually, that looks like a response you'd get if you'd not logged into the app the first time.. if you've not installed the librelinkup app on a phone and logged in to it with the same credentials, can you give that a try? I think once you've done that, you'll be set.

**Comment by Kanzll** [comment] 2024-11-02 18:35
```
{
    "status": 0,
    "data": {
        "user": {
            "id": "xx",
            "firstName": "xx",
            "lastName": "xx",
            "email": "xx",
            "country": "CA",
            "uiLanguage": "fr-CA",
            "communicationLanguage": "fr-CA",
            "accountType": "pat",
            "uom": "0",
            "dateFormat": "2",
            "timeFormat": "2",
            "emailDay": [
                1
            ],
            "system": {
                "messages": {
                    "firstUsePhoenix": 1702669062,
                    "firstUsePhoenixReportsDataMerged": 1702669062,
                    "lvWebPostRelease": "3.16.19",
                    "webRegister": 1702669062,
                    "welcomeScreen": 1702669161
                }
            },
            "details": {},
            "twoFactor": {
                "primaryMethod": "",
                "primaryValue": "",
                "secondaryMethod": "",
                "secondaryValue": ""
            },
            "created": 1702669000,
            "lastLogin": 1702669000,
            "programs": {},
            "dateOfBirth": xx,
            "practices": {
                "xx": {
                }
            },
            "devices": {
                "xx": {
                    "id": "xx",
                    "nickname": "",
                    "sn": "xx",
                    "type": 40000,
                    "uploadDate": 1730557385
                }
            },
            "consents": {
                "llu": {
                    "policyAccept": 1730569693,
                    "touAccept": 1730569688
                },
                "realWorldEvidence": {
                    "policyAccept": 1702669061,
                    "touAccept": 0,
                    "history": [
                        {
                            "policyAccept": 1702669061
                        }
                    ]
                }
            }
        },
        "messages": {
            "unread": 0
        },
        "notifications": {
            "unresolved": 0
        },
        "authTicket": {
            "token": "xxx",
            "expires": 1746124343,
            "duration": 15552000000
        },
        "invitations": null,
        "trustedDeviceToken": ""
    }
}
```

**Comment by robberwick** [comment] 2024-11-02 18:51
that's strange - it's a completely different data structure than is usually returned to librelinkup users.. Are you using your libreview account credentials, or credentials for a librelinkup account? I ask because they're not the same thing, and this wrapper is intended to work with LLU accounts only.

So, for instance, i have 2 accounts: 1 LibreView account for my libre sensor which i use to log into the Librelink app on my phone, and a separate account for the LibreLinkup app, which is _also_ installed on my phone. Then, in the LibreLink app, I share my data with my LLU account email, and i can use those credentials with PyLibreLinkUp to access the monitored values.

Looking at that JSON response, i'd guess that you're trying to access the LLU data with the same login details you'd use in the LibreLink app, which is why you're being returned an odd data structure which is missing things like the graph data etc.

Obviously, we could do a better job of detecting that and returning a more appropriate message, and i'll look into doing that using the data you've provided above.

**Comment by Kanzll** [comment] 2024-11-02 18:59
I'm so sorry ! I'm using my libreView credantials :(
I'll create an LLU account, and I'll let,s you know with results.
Thank you

**Comment by robberwick** [comment] 2024-11-02 19:14
No problem! It's interesting that you can get any data at all using your libre view details.. I might have to investigate that!

Yeah, let me know how you get on. I definitely need to handle that case though, because you won't be the last person to fall foul of that confusion. They really could have made it easier to tell those two services apart.. 😕

**Comment by Kanzll** [comment] 2024-11-02 19:47
Yes, it's confused !
I created a new LLU account, and used it in your test script, the respond change a little
```
{
    "status": 0,
    "data": {
        "user": {
            "id": "xx",
            "firstName": "xx",
            "lastName": "xx",
            "email": "xx",
            "country": "CA",
            "uiLanguage": "en",
            "communicationLanguage": "en",
            "accountType": "pat",
            "uom": "0",
            "dateFormat": "2",
            "timeFormat": "2",
            "emailDay": [
                1
            ],
            "system": {
                "messages": {
                    "appReviewBanner": 1730575099,
                    "firstUsePhoenix": 1730575050,
                    "firstUsePhoenixReportsDataMerged": 1730575050,
                    "lluNewFeatureModal": 1730575069,
                    "lluOnboarding": 1730575088,
                    "lvWebPostRelease": "3.19.10"
                }
            },
            "details": {},
            "twoFactor": {
                "primaryMethod": "",
                "primaryValue": "",
                "secondaryMethod": "",
                "secondaryValue": ""
            },
            "created": xx,
            "lastLogin": xx,
            "programs": {},
            "dateOfBirth": xx,
            "practices": {},
            "devices": {},
            "consents": {
                "llu": {
                    "policyAccept": 1730575050,
                    "touAccept": 1730575050
                }
            }
        },
        "messages": {
            "unread": 0
        },
        "notifications": {
            "unresolved": 0
        },
        "authTicket": {
            "token": "xx",
            "expires": 1746127527,
            "duration": 15552000000
        },
        "invitations": [
            "cxxx"
        ],
        "trustedDeviceToken": ""
    }
}
```
but script still raise error on line 66 (pylibrelinkup.py) -> login_response = LoginResponse.model_validate(data)

**Comment by robberwick** [comment] 2024-11-02 19:54
Ok I'll have to dig into this a little more then.. I'll see if I can try to replicate your issue here and take it from there.

Out of interest, are you providing a value for api_url to the PyLibreLinkUp constructor, or leaving it out and using the default?

**Comment by Kanzll** [comment] 2024-11-02 19:57
> Ok I'll have to dig into this a little more then.. I'll see if I can try to replicate your issue here and take it from there.
> 
> Out of interest, are you providing a value for api_url to the PyLibreLinkUp constructor, or leaving it out and using the default?

using default, I tested a Canadian url but this give the same error

**Comment by robberwick** [comment] 2024-11-03 09:39
I think i see what the problem might be - that response is the same data structure that is returned when you've [successfully accepted the terms of use](https://libreview-unofficial.stoplight.io/docs/libreview-unofficial/2820132fdbd4f-accept-terms#Responses).. you have a valid `authTicket` key with a `token` in there.. so i think i'm just being too strict on what a login success looks like, and should instead just look for those token values. If they're present, you've logged in.

you should be able to see if that theory holds up for you by editing the authenticate method in `/opt/anaconda3/lib/python3.12/site-packages/pylibrelinkup/pylibrelinkup.py` from:

```python
        try:
            login_response = LoginResponse.model_validate(data)
            self._set_token(login_response.data.authTicket.token)
            self._set_account_id_hash(login_response.data.user.id)

        except ValidationError:
            raise AuthenticationError("Invalid login credentials")
```

to

```python
        login_response_data = data.get("data", {})
        token = login_response_data.get("authTicket", {}).get("token")
        user_id = login_response_data.get("user", {}).get("id")
        
        if not token or not user_id:
            raise AuthenticationError("Invalid login credentials")
        
        self._set_token(token)
        self._set_account_id_hash(user_id)
```

**Comment by robberwick** [comment] 2024-11-03 10:55
ok, i managed to reproduce it. It looks like either the login response has changed, so it's not validating against what i was expecting, or it can just be in a slightly different form to what i've seen before. Either way, i have a test that i can use to write the patch, so i'll do that and put out a point release asap.

**Comment by robberwick** [comment] 2024-11-03 17:07
It seemed like just a sensible thing to do, so i went ahead and merged the patch, along with an update to also handle the case where the user still needs to verify their email address. It's present in [v0.5.0](https://github.com/robberwick/pylibrelinkup/releases/tag/v0.5.0), and available for download [from pypi](https://pypi.org/project/pylibrelinkup/0.5.0/)

**Comment by Kanzll** [comment] 2024-11-03 18:38
Thanks @robberwick for update, but strangely I tested authentification yesterday night (with 0.4 version), and  it worked ! I don't know if it had to wait a little bit after creating the LLU account.
Now, I have another problem with pydantic package and validation, on read method, Do you want to continue on this thread or create a new issue ?

**Closed** 2024-11-03 18:42 UTC
Labels: bug

**Comment by realcodfish** [comment] 2025-01-26 11:50
Like Kanzil, I'm still getting a simple: 'pylibrelinkup.exceptions.AuthenticationError: Invalid login credentials'. I'm using 0.7.0 with a LLU account. I ran the test script, and the output is the same in structure, as above, except that two-factor fields are present for me (and I assume Kenzil has those off). Is 2FA an issue?

**Comment by robberwick** [comment] 2025-01-26 12:08
Hi @realcodfish Yes, 2FA may well be an issue, as I've not accounted for that workflow at all. I wasn't even aware that it was a thing with LLU ;-)

Can you open a new issue with details of your error, and the payload that you're being returned from the API response?

**Comment by realcodfish** [comment] 2025-01-26 12:26
Ahhh yes perhaps more of a feature request issue than any defect. I noted no obvious way of attaching a 2FA code in the API but the login attempt didn't trigger an SMS from the server either. Will post the payload in a new issue.

**Comment by robberwick** [comment] 2025-01-26 12:48
awesome. thanks @realcodfish 👍
